### ISSUE TITLE
[🚀 | Feature request]: Go to a file using a link inside Parsec app

### ISSUE THREAD

**Issue by Landeers** [Scille/parsec-cloud#10285]
Was present on V2. Would be usefull on web as link do not work for now to redirect to web.
![Image](https://github.com/user-attachments/assets/e0c7adf6-886d-4e65-bfff-91874a01bcb6)

**Comment by mmmarcos** [comment]
Ideally we should add support for http links, but this button can allow us to quickly address the issue (file links not available on web). 

We can even detect automatically if the clipboard contains a file link.

**Comment by mmmarcos** [comment]
Alternative to fully support web links: #10379

**Comment by NicoTuxx** [comment]
Problem solved by alternative in #11281

**Comment by Landeers** [comment]
Not solved, shared links use `parsec3://` url, therefore, the links are still unusable in the web version.
In addition, the links contain the server domain, not the client domain, so the devices will be untraceable in any case.
